export const GET_RANDOM_JOKE = "GET_RANDOM_JOKE";
export const GET_RANDOM_JOKE_FAIL = "GET_RANDOM_JOKE_FAIL";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_CHOSEN_CATEGORY = "GET_CHOSEN_CATEGORY";
